devices:
    common: []
    debug: []
    release: []
dockercomposefile:
    common: ''
    debug: ''
    release: ''
extraparms:
    common: {}
    debug: {}
    release: {}
id: 2dbec6c6-466b-4abe-a176-001f1921230d
images:
    debug: ''
    release: ''
imagetags:
    debug: pythonconsole_arm32v7-debian-python3_bullseye_debug_2dbec6c6-466b-4abe-a176-001f1921230d
    release: pythonconsole_arm32v7-debian-python3_bullseye_release_2dbec6c6-466b-4abe-a176-001f1921230d
modificationdate: '2022-08-15T20:41:27.047042'
networks:
    common: []
    debug: []
    release: []
otapackagename: ''
otapackageversion: 1.0.0
platformid: arm32v7-debian-python3_bullseye
ports:
    common: {}
    debug: {}
    release: {}
privatekey: '-----BEGIN RSA PRIVATE KEY-----

    MIIEpAIBAAKCAQEAlzUhZGa2UuPIpL2aCeQUm4WrDQ28oOcAv9e3bMfa27R/Ti8y

    xk+TjmMuLEYbVBiWkF4nYKlvbp6j19QCSQyisCP1yOTIMftuXNSPaIXSmIvkQRV7

    8ZxKo7+7VqBpogpAM7dLBvenOt/IVENtE3+2TO/ZBXLreniOJBQqzotgVMLrg6fH

    8kX4WD/B5P2GDU5LjW3VWQh1B+ApmheH0Ev0iUkcLpPmkA0r3B1T+xZCHva63MmU

    axyo7ciis/FkUoaz0wGRh5Sn6hyUX+0SKHTsu1OEsrUNBAmuwiWTxI473lf0PvvL

    lsblsAWll1MRxJegHPFXwJ9urOu/tlutsI4lPwIDAQABAoIBACWxFExTQDKkXkEW

    lD3P8YUdClj8Kh+PxcOMkcgXf4pR0YQbRtRhRL5zIbDenvRVFr8RAU7anZDdEal8

    yz8LW8h9hkiYIwE2lDmmsMLUzPzCrli88sL0+zQbWKcM4JgIZx2dHKI1fKWz39uF

    XTzFkptWFGqDzYgfYgtDTbJj0tT9yWoy6Gw3bUswxxqzGdlrc7uyiNBOaF0EAk87

    Rooq+fdliOqFCChVrf3ZrYAIVyfxWiPLbXEpzDjhDXP5cYCF3jbTB9Q9pz9vlsP0

    64c+GBPE5f0cWJXqZetLduBI6B9/8UqQeCIIfNJtSg8HCEd7T7nMTzAo9ULawaM2

    VebrHrUCgYEA0kuegyPqlWtEmyJ8GgHsTwWa9xPFNT+wCccVKpNi7gL5W9qYr+ug

    Oucw6ckXFeUh5mqIvIP4gjXme+PEywN8pB+bKU3WYQVBPjxjAKR6qQH3B2aER/QN

    KLjoGqzXeTnjFDwgX5PCQeM0H+FBWM5M7YbKPAn3+wQlHiN8eRFRhHUCgYEAuBH9

    vcOiB1CEvbKez6k7762v5kXWypuHfV14ygvklLBU7uxYgSxGaw9taIfrlO5o0fPQ

    u7/iDh7rhnEKaAaY0LPfx7GDPR8/U4tubxDCQuFINzgkjTV8a57c/Mx3yEUBxWsX

    vf3aUvkr/urCduk2oNyPOQqLIPQkf0WJ6t16vGMCgYEAtISHGCl/mC3RYZ4Ti7u0

    3wx/vrJw6cm20l3b1IVaOdfBt9CImxKXo5iLi1O8BmZ/WCyBHdnnO9cK97RIXMCs

    gLJE3grcCMKbA9KQZZ/LT0LJi8e7q4xas2cujp9qA7zmKZuHaqQK78YaG3egQZwt

    uwOmnC0ueoJPXnS1x7NPF3UCgYEAiMc9sRQ9Q4guizO+1PqhghGjgs5ktHtr69lY

    V3MM8PwysLPJdHss/IMjPqi5gxrBozm04r7MQMfzJhy7qd81EOiIokAjEHk2umMC

    td9TKxVyby3140RaZzJObj+VxqiYj1Vr+A85e6ySZ8OUq33SzSf3+V//UIZ61GQc

    /vyDJpcCgYApY809WNwfoy5iiHciXuqX3OYp0fHDjKvKWE1Ks8Pi5pP9fAfp17A5

    Q6mSvsEEjT9iljYrhLQkQ6J4h3kCQ61MUNPqwDJBA8AIqP/MdOqGUpfbbeTlJeAa

    H4eWJ+is+aq+l7XhClpSYibTqmA+i5og9VfYd7yTkEwkqXdLaBJ4GA==

    -----END RSA PRIVATE KEY-----

    '
props:
    common:
        appargs: ''
        appname: pythonConsole
        arg: ''
        buildcommands: ''
        buildfiles: ''
        command: ''
        devpackages: ''
        env: ''
        expose: ''
        extrapackages: ''
        language: python
        main: main.py
        preinstallcommands: ''
        runtime: python3
        sdkpostinstallcommands: ''
        sdkpreinstallcommands: ''
        targetcommands: ''
        targetfiles: ''
    debug:
        arg: 'ARG SSHUSERNAME=#%application.username%#

            '
    release: {}
publickey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCXNSFkZrZS48ikvZoJ5BSbhasNDbyg5wC/17dsx9rbtH9OLzLGT5OOYy4sRhtUGJaQXidgqW9unqPX1AJJDKKwI/XI5Mgx+25c1I9ohdKYi+RBFXvxnEqjv7tWoGmiCkAzt0sG96c638hUQ20Tf7ZM79kFcut6eI4kFCrOi2BUwuuDp8fyRfhYP8Hk/YYNTkuNbdVZCHUH4CmaF4fQS/SJSRwuk+aQDSvcHVP7FkIe9rrcyZRrHKjtyKKz8WRShrPTAZGHlKfqHJRf7RIodOy7U4SytQ0ECa7CJZPEjjveV/Q++8uWxuWwBaWXUxHEl6Ac8VfAn26s67+2W62wjiU/
sdkimages:
    debug: ''
    release: ''
sdkimagetags:
    debug: ''
    release: ''
sdksshaddress:
    debug: null
    release: null
shutdownscript:
    common: ''
    debug: ''
    release: ''
startupscript:
    common: ''
    debug: ''
    release: ''
username: torizon
volumes:
    common: {}
    debug: {}
    release: {}
